# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    eclipse_4_8:
      ECLIPSE_TARGET_PLATFORM: 'Eclipse-4.8'
    eclipse_2020_09:
      ECLIPSE_TARGET_PLATFORM: 'Eclipse-2020-09'
    eclipse_2020_12:
      ECLIPSE_TARGET_PLATFORM: 'Eclipse-2020-12'
    eclipse_2021_03:
      ECLIPSE_TARGET_PLATFORM: 'Eclipse-2021-03'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    pulishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: '-Dtarget.platform=$(ECLIPSE_TARGET_PLATFORM) clean verify'
